### ISSUE TITLE
[Android Log] Rules used to determine log files' create time fail when file names are not in the desirable format 

### ISSUE THREAD

**Issue by brianxcli** [AgoraIO-Usecase/Tools#1]
"CheckUtil" tool class checks a log file's create time by parsing its file name.

The class does not filter out file names that are not in strict format of log file's naming rule,  for example, contains ".log" except the extension name, or the substring between underscore character "_" and the suffix ".log" is not a long integer value at all (say, an arbitrary series of non-digital characters)

**Comment by Chen-Alexander** [comment]
> "CheckUtil" tool class checks a log file's create time by parsing its file name.
> 
> The class does not filter out file names that are not in strict format of log file's naming rule, for example, contains ".log" except the extension name, or the substring between underscore character "_" and the suffix ".log" is not a long integer value at all (say, an arbitrary series of non-digital characters)

OK,it has be fixed. thanks.
